import { Link, useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { AuthShell } from './Login.jsx';
import { useAuthStore } from '../store/useAuthStore.js';

export default function AuthForm({ mode }) {
  const action = useAuthStore((s) => mode === 'signup' ? s.signUp : mode === 'forgot' ? s.resetPassword : s.updatePassword);
  const error = useAuthStore((s) => s.error); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [name, setName] = useState(''); const [message, setMessage] = useState(''); const [formError, setFormError] = useState(''); const [busy, setBusy] = useState(false); const nav = useNavigate();
  const title = mode === 'signup' ? 'create account' : mode === 'forgot' ? 'reset access' : 'set new password';
  async function submit(e) { e.preventDefault(); if (busy) return; setFormError(''); setMessage(''); if (mode === 'signup' && password !== confirmPassword) { setFormError('Passwords do not match.'); return; } setBusy(true); const result = mode === 'signup' ? await action(email, password, name) : mode === 'forgot' ? await action(email) : await action(password); setBusy(false); if (!result?.error) { if (mode === 'signup' && result.data?.session) { nav('/dashboard'); return; } setMessage(mode === 'forgot' ? 'Check your email for a reset link.' : mode === 'signup' ? 'Account created. Please sign in.' : 'Password updated.'); if (mode === 'reset') nav('/dashboard'); } }
  return <AuthShell title={title} subtitle="your data belongs to you"><form onSubmit={submit} className="space-y-4">{mode === 'signup' && <Field label="Display name" value={name} set={setName}/>} {mode !== 'reset' && <Field label="Email" type="email" value={email} set={setEmail}/>} {mode !== 'forgot' && <Field label="Password" type="password" value={password} set={setPassword}/>} {mode === 'signup' && <Field label="Confirm Password" type="password" value={confirmPassword} set={setConfirmPassword}/>} {(formError || error) && <p className="text-sm text-nebula-red">{formError || error}</p>}{message && <p className="text-sm text-nebula-green">{message}</p>}<button disabled={busy} className="btn-neon w-full">{busy ? 'creating account…' : mode === 'signup' ? 'create account' : 'continue'}</button></form><Link to="/login" className="mt-6 block text-center text-xs text-slate-400 hover:text-nebula-violet">back to sign in</Link></AuthShell>;
}
function Field({ label, type='text', value, set }) { return <label className="block"><span className="mb-2 block font-mono text-[11px] uppercase tracking-widest text-slate-400">{label}</span><input required type={type} value={value} onChange={(e)=>set(e.target.value)} className="w-full rounded-lg border border-nebula-violet/20 bg-black px-4 py-3 text-slate-100 outline-none focus:border-nebula-violet" /></label>; }
